ホーム画面にHelloの表示とリンクの追加
gp1000-dev/gp-attendance pull request #106
Opened 2022-06-24 08:11 UTC by gp-nakai

ホーム画面にHelloを表示し、ユーザー情報と勤怠用法のリンクを追加しました。

2022-06-24 08:29 UTC, gp-sato requested changes
佐藤、レビュー終わりました。

2022-06-24 08:29 UTC, gp-sato commented on app/Http/Controllers/HomeController.php
> +        return view('home', ['user' => $user]);
Auth() はビューのなかで出来ます。

2022-06-24 08:29 UTC, gp-sato commented on resources/views/home.blade.php
> +                <li><a href="/attendances">勤怠情報</a></li>
リンクはルーティング(web.php)の設定を使ってください。route('name') と書いた方がよいです。

2022-06-24 08:41 UTC, gp-sato requested changes
佐藤、レビューしました。

2022-06-24 08:41 UTC, gp-sato commented on resources/views/home.blade.php
> +                <li><a href={{route('attendances.index')}}>勤怠情報</a></li>
href属性の値はダブルクォーテーションで囲ってください。

2022-06-27 01:30 UTC, gp-yamada approved these changes
OKです。

2022-06-27 01:32 UTC, gp-yamada approved these changes

2022-06-27 01:33 UTC, gp-yamada approved these changes

2022-06-27 01:33 UTC, gp-yamada approved these changes

2022-06-27 01:38 UTC, merged