Nakai/#124 admin show users
gp1000-dev/gp-attendance pull request #127
Opened 2022-06-30 08:00 UTC by gp-nakai

2022-06-30 23:22 UTC, gp-yamada requested changes

2022-06-30 23:22 UTC, gp-yamada commented on resources/views/admin/users/index.blade.php
> +                                <?php if ($user->gender === 'male'): ?>
<?php if 〜 ではなく
@if 〜 @else 〜 @endif を使ってください。

2022-06-30 23:28 UTC, gp-yamada requested changes
要修正

2022-06-30 23:28 UTC, gp-yamada commented on app/Http/Controllers/Admin/AdminUsersController.php
> +        $users = USER::all();
USER::all() ?
User::all() では？

2022-06-30 23:28 UTC, gp-yamada commented on resources/views/admin/users/index.blade.php
>                                  <td>{{$user->birthdate->format('Y年n月j日')}}</td>
年齢を表示してください（画面仕様参照）
参考：https://www.wakuwakubank.com/posts/421-php-carbon/

2022-06-30 23:31 UTC, gp-yamada requested changes

2022-06-30 23:31 UTC, gp-yamada commented on resources/views/admin/users/index.blade.php
>                                  <?php endif; ?></td>
@if 〜 @else 〜 @endif
を利用してください。

2022-07-01 06:14 UTC, gp-yamada requested changes

2022-07-01 06:14 UTC, gp-yamada commented on resources/views/admin/users/index.blade.php
> +                            @endphp
use Carbon\Carbon は必要無いと思います。
無くても正常動作するなら削除してください。

2022-07-01 06:14 UTC, gp-yamada commented on resources/views/admin/users/index.blade.php
> +                                <td>{{$user->birthdate->format('Y年n月j日')}}({{$user->birthdate->age}}歳)</td>
OKです。

2022-07-01 07:31 UTC, gp-yamada approved these changes

2022-07-01 08:06 UTC, gp-yamada requested changes

2022-07-01 08:06 UTC, gp-yamada commented on resources/views/admin/users/index.blade.php
>                                  <td></td>
この位置にボタンを表示させてください（リンク先は空でいい）

2022-07-04 12:19 UTC, gp-sato commented
@foreach文が<thead>タグ内に書かれているため、ユーザー情報に下線が引かれています。<tbody>を用意してあるので、そちらに移してはどうでしょうか。

2022-07-05 04:40 UTC, gp-yamada commented
@gp-nakai 佐藤さん（＠gp-sato）の指摘どおり、<tbody>タグの中に移動してください。
```
<table>
    <thead>
        <tr>
            <td>    </td>
        </tr>
    </thead>
    <tbody>
        @foreach
        <tr>
            <td>    </td>
        </tr>
       @endforeach
    </tbody>
</table>
```

2022-07-05 05:12 UTC, gp-yamada approved these changes
OKです。

2022-07-05 05:12 UTC, merged