Sato/#129 delete confirm dialog
gp1000-dev/gp-attendance pull request #132
Opened 2022-07-01 07:22 UTC by gp-sato

取消しの前に確認のダイアログを表示して、[OK]を押した時は取消すようにしました。

2022-07-01 08:03 UTC, gp-yamada requested changes

2022-07-04 08:37 UTC, gp-sato commented on resources/views/layouts/app.blade.php
> +@yield('script')
@yield('script') を body の最後に移動しました。

2022-07-04 08:41 UTC, gp-sato commented on resources/views/attendances/edit.blade.php
>  </script>
status ではなく absence のままだったため、JavaScript を有効にするとバグになります。削除しました。
別のissueでjQueryに書き換える予定です。削除する予定のコードなので問題ないと思われます。

2022-07-05 04:51 UTC, gp-yamada approved these changes

2022-07-05 04:52 UTC, merged