Sato/#90 select time disabled jQuery
gp1000-dev/gp-attendance pull request #133
Opened 2022-07-04 08:20 UTC by gp-sato

勤怠登録と変更画面で「休業」を選んだ時、開始時刻と終了時刻が選択できないようにしました。
JavaScript を jQuery に変更しました。
app.blade.php で jQuery を外部から読み込むコードを入れました。問題があればお願いします。

2022-07-14 00:08 UTC, gp-yamada requested changes

2022-07-14 00:08 UTC, gp-yamada commented on resources/views/attendances/create.blade.php
> +});
- `$(() => { });` で囲う必要はないと思います。
- `$('#status').change()` は `$('#status').on('change', () => {})` に変えてください。理由はjQuery関連サイトを参考にしてください。

2022-07-14 00:08 UTC, gp-yamada commented on resources/views/attendances/edit.blade.php
- `$(() => {` は不要だと思います。
- `==` は `===` にしてください。

2022-07-14 04:56 UTC, gp-sato commented on resources/views/attendances/create.blade.php
> +});
$(() => { }); を取り除きました。
$('#status').change() は $('#status').on('change', () => {}) に変更しました。
== を === に修正しました。

2022-07-14 05:00 UTC, gp-sato commented on resources/views/attendances/edit.blade.php
`$(() => { });` を取り除きました。
`$('#status').change()` は `$('#status').on('change', () => {})` に変更しました。
`==` を `===` に修正しました。

2022-07-20 22:10 UTC, gp-yamada approved these changes

2022-07-20 22:13 UTC, merged