Sato/#31 add items registration page
gp1000-dev/gp-attendance pull request #71
Opened 2022-05-02 08:01 UTC by gp-sato

新規登録ページのビューを作りました。
名前を削除して、
姓、名前、姓カナ、名前カナ、性別、誕生日を追加しました。
誕生日は年、月、日で分けてあります。コントローラーで日付データに変換しました。

2022-05-05 22:18 UTC, gp-yamada requested changes
修正点があります。

2022-05-05 22:18 UTC, gp-yamada commented on resources/views/auth/register.blade.php
> +
- ラジオボタンを横並びにしてください。form-check-inlineクラスを使います。（https://getbootstrap.jp/docs/5.0/forms/checks-radios/）
- old値が適用されていません。

2022-05-05 22:18 UTC, gp-yamada commented on resources/views/auth/register.blade.php
> +                        </div>
- 月・日を未入力でエラー表示させると「！」マークで入力値が隠れてしまいます。

2022-05-05 22:22 UTC, gp-yamada requested changes
修正点があります。

2022-05-05 22:22 UTC, gp-yamada commented on app/Http/Controllers/Auth/RegisterController.php
>              'password' => ['required', 'string', 'min:8', 'confirmed'],
- パスワードのValidationルールをユーザー情報変更と同じにしてください。（英数字混在）

2022-05-05 23:00 UTC, gp-yamada requested changes

2022-05-05 23:00 UTC, gp-yamada commented on resources/views/auth/register.blade.php
- メールアドレスに＠無しで入力するとView側のエラーが出てControllerのバリデーションが確認できません。これはtype="email"としているためなので、type="text" に変更してください。

2022-05-06 07:52 UTC, gp-sato commented on resources/views/auth/register.blade.php
> +
form-check-inlineクラスで横並びにしました。
エラーメッセージの表示箇所を調整しました。
old値を用いてチェックの保持をしました。

2022-05-06 07:55 UTC, gp-sato commented on resources/views/auth/register.blade.php
> +                        </div>
年月日の入力欄の幅を調節しました。
ラベルと入力欄の幅の比率を調整しました。
他の入力欄も年月日に合わせて調節しました。
氏名と氏名カナの入力欄の幅を調節しました。
年月日、氏名、氏名カナのエラーメッセージの表示を欄の下部にまとめて表示するようにしました。

2022-05-06 07:58 UTC, gp-sato commented on app/Http/Controllers/Auth/RegisterController.php
>              'password' => ['required', 'string', 'min:8', 'confirmed'],
パスワードのバリデーションルールをPasswordクラスを使った記述に変更しました。
confirmedルールを最後にしました。
バリデーションチェックをしました。最小値ルールは限界値チェックをしました。

2022-05-06 07:59 UTC, gp-sato commented on resources/views/auth/register.blade.php
メールアドレスではない文字列を入力したときに、Controllerのバリデーションで弾かれることを確認しました。

2022-05-06 08:01 UTC, gp-sato commented on resources/views/auth/register.blade.php
> +                        </div>
レスポンシブ対応でスマホ表示で表示が崩れないことを確認しました。

2022-05-09 00:39 UTC, gp-yamada approved these changes

2022-05-09 00:49 UTC, merged